#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def getTotalX(a, b):
    result =0
    max_a=max(a)
    min_b=min(b)
    prb=max_a
    while prb<=min_b:
        if ((check_a(prb,a)) and (check_b(prb,b))):
            result+=1
        prb+=max_a
    return(result)
    
def check_a(n,a):
    for i in a:
        if ((n % i)!=0):
            return False
    return True

def check_b(n,b):
    for i in b:
        if ((i % n)!=0):
            return False
    return True

    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()
